version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: sample
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - db_data:/var/lib/postgresql/data/

  api:
    image: node:12.16.0
    restart: always
    working_dir: /app
    command: npm run start:dev
    environment: 
      STENO_DB_HOST: db
      STENO_DB_PORT: 5432
      STENO_DB_USER: postgres
      STENO_DB_PASSWORD: postgres
      STENO_DB_NAME: sample
    ports: 
      - '${STENO_PORT-8080}:8080'
    volumes: 
      - ./:/app
    depends_on: 
        - db

volumes:
  db_data: