POST http://localhost:8000/steno/executeSql
Content-Type: text/plain

< ./test.sql
###

POST http://localhost:8000/steno/console
Content-Type: application/json

{
    "name":"insert",
    "group":"test",
    "sql":"INSERT INTO steno_test_table (\ntest_name,\ntest_version,\ntest_create_dt\n)\nVALUES\n(\n:test_name,\n:test_version,\n:test_create_dt\n) RETURNING test_id;"
}

###

POST http://localhost:8000/steno/console
Content-Type: application/json

{
    "name": "select",
    "group": "test",
    "sql": "SELECT * FROM steno_test_table WHERE test_name = :test_name"
}

###

POST http://localhost:8000/steno/console/test
Content-Type: application/json

{
    "mutation": {
        "test:insert": {
            "params": {
                "test_name": "${name}",
                "test_version": "${version}",
                "test_create_dt": "${createDate}"
            }
        }
    },
    "query": {
        "select@test:select": {
            "params": {
                "test_name": "${name}"
            }
        }
    }
}

###
POST http://localhost:8000/steno/api/test
Content-Type: application/json

{
    "name": "test1",
    "version": 1,
    "createDate": "2020-01-01 01:01:01"
}

###

POST http://localhost:8000/steno/api
Content-Type: application/json

{
    "mutation": {
        "test:insert": {
            "params": {
                "test_name": "testd ss",
                "test_version": "2",
                "test_create_dt": "2012-01-01 01:01:01"
            }
        }
    },
    "query": {
        "select@test:select": {
            "paginated": true,
            "page": 2,
            "size": 1,
            "params": {
                "test_name": "${name}"
            }
        },
        "select1@test:select": {
            "singleResult": true,
            "params": {
                "test_name": "${name}"
            }
        }
    },
    "variables": {
        "name": "test ss"
    }
}

###

POST http://localhost:8000/steno/api
Content-Type: application/json

{
    "query": {
        "select@test:select": {
            "paginated": true,
            "page": 1,
            "size": 3,
            "params": {
                "test_name": "${name}"
            },
            "orderBy": {
                "columns": "test_id, test_name",
                "asc": true
            }
        }
    },
    "variables": {
        "name": "test ss"
    }
}

###

POST http://localhost:8000/steno/api
Content-Type: application/json

{
    "mutation": {
        "insert@test:insert": {
            "params": "${testArray}"
        }
    },
    "variables": {
        "testArray": [
            {
                "test_name": "testd ss",
                "test_version": "2",
                "test_create_dt": "2012-01-01 01:01:01"
            },
            {
                "test_name": "testd ss",
                "test_version": "2",
                "test_create_dt": "2012-01-01 01:01:01"
            },
            {
                "test_name": "testd ss",
                "test_version": "2",
                "test_create_dt": "2012-01-01 01:01:01"
            },
            {
                "test_name": "testd ss",
                "test_version": "2",
                "test_create_dt": "2012-01-01 01:01:01"
            },
            {
                "test_name": "testd ss",
                "test_version": "2",
                "test_create_dt": "2012-01-01 01:01:01"
            }
        ]
    }
}


###

POST http://localhost:8000/steno/api
Content-Type: application/json

{
    "mutation": {
        "insert1@test:insert": {
            "priority": 999,
            "params": "${testOn3}"
        },
        "insert2@test:insert": {
            "priority": 1,
            "params": "${testArray}"
        }
    },
    "variables": {
        "insert1": "1",
        "version": {
            "value": 1
        },
        "testOn3": {
            "test_name": "testd 11",
            "test_version": "${version.value}",
            "test_create_dt": "2012-01-01 01:01:01"
        },
        "testArray": [
            {
                "test_name": "testd 21",
                "test_version": "${insert1.returned.test_id}",
                "test_create_dt": "2012-01-01 01:01:01"
            },
            {
                "test_name": "testd 21",
                "test_version": "${insert1.returned.test_id}",
                "test_create_dt": "2012-01-01 01:01:01"
            }
        ]
    }
}

###
GET http://localhost:8000/steno/tables